### PR TITLE
Matt/judgepage fixes

### PR DESCRIPTION
**Pull request by mvb0005**
Added the hyperlinks and implemented my fix to the table problem.

### CODE REVIEW

**Comment by BrandonLMorris** [comment]
lgtm. I can't run the site locally right now, so I'll need someone who can ( @Mac-Genius ) to sign off on it.

Protip: Don't put spaces in your branch name. Use -'s

Question: does this fix the problems in #114?

**Comment by Mac-Genius** [comment]
I will try to look at it later today.

**Comment by Mac-Genius** [comment]
I have looked over your changes and tested them, and everything seems to be good!

**Comment by Mac-Genius** [comment]
Are we good to merge?

**Pull request merged**
